pages:
  stage: deploy
  script:
    # Создаем целевую папку public, которую ожидает GitLab
    - mkdir public
    # Копируем всё содержимое из папки web в папку public
    - cp -r web/* public/
  artifacts:
    paths:
      - public
  only:
    - main # или master, в зависимости от имени вашей главной ветки
