name: Deploy GitHub Pages & Auto Update Telegram JS

on:
  push:
    branches:
      - main # Сборка при пуше в ветку main
  schedule:
    # Запуск по расписанию каждый понедельник в 00:00 по UTC (3:00 по МСК)
    - cron: '0 0 * * 1'
  workflow_dispatch: # Позволяет запустить процесс вручную кнопкой в интерфейсе GitHub

permissions:
  contents: write # Даем экшену право записывать изменения (делать коммиты)
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # СКАЧИВАЕМ ФАЙЛ НАПРЯМУЮ В ПАПКУ JS
      - name: Download fresh Telegram Web App JS
        run: |
          mkdir -p js
          curl -o js/telegram-web-app.js https://telegram.org/js/telegram-web-app.js

      # ПРОВЕРЯЕМ ИЗМЕНЕНИЯ И ДЕЛАЕМ КОММИТ
      - name: Commit and Push if updated
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          
          if git diff --quiet js/telegram-web-app.js; then
            echo "Файл js/telegram-web-app.js не изменился."
          else
            echo "Обнаружена новая версия скрипта! Делаем коммит..."
            git add js/telegram-web-app.js
            git commit -m "chore: автоматическое обновление js/telegram-web-app.js [skip ci]"
            git push
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
